#! /bin/bash
# blackboard typefaces by Anthony Phan.
# file: @compile (stupid compilation script)
# last modification: 09.08.2001.
# 
# This script is helful for me. I just type 'bash @compile'
# then drink my coffee. It produces metrics and bitmaps (pk)
# for the 'ljfour' mode, then it wipes out temporary files
# and put the useful stuff in some directory...
# PLEASE CHANGE THE THIS FILE FOR YOUR OWN NEEDS.

for xx in 17 12 10 9 8 7 6 5
do
    mf "\mode=ljfour; input mbb$xx"; gftopk mbb$xx.600gf;
    mf "\mode=ljfour; mag=1.2; input mbb$xx"; gftopk mbb$xx.720gf;
    mf "\mode=ljfour; input mbbx$xx"; gftopk mbbx$xx.600gf;
    mf "\mode=ljfour; mag=1.2; input mbbx$xx"; gftopk mbbx$xx.720gf;
done;

for fontxx in mbbheb10 mbbgr10 mbbi10 mbbsl10 mbbsc10 mbbr10 mbbcr10
do
    mf "\mode=ljfour; input $fontxx"; gftopk $fontxx.600gf;
    mf "\mode=ljfour; mag=1.2; input $fontxx"; gftopk $fontxx.720gf;
done;

mv *.tfm ../tfm; mv *pk ../pk; rm *gf; rm *.log;

